#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "73ecd1abee4a44a18e78f5ad24763d90" }
]

[assets]
directory = "./public"
